language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: nosetests --with-cov --cov-config .coveragerc --cov-report term-missing
notifications:
  email: false
  slack:
    secure: RhS3cqg98l/l39h4nIpSQOh9n7z8EwlyBtW8bW4bOmSV+Bx27i3WreB5Et/y2GeUuu8UxSflS8d2IjRUoyq7y1hmaaZK2YW3prKS3gyma3/u2jkv0BYCDG/RON8kgi4QZtur0eH77bi76UbpUu6g6TwBh/Dz0vzdMOEtKiZNWQXf23PLMf+alEVyQSxkOQcxuRX4OdxcixZy8RG4tc0CVUpDcWv7kEkRcH//jbePrybOEHd0lq/lBWhXLRnoYNtBaO8QsKfstE8ZEzdRxrzaGqkyJEtmPu2RctorQsf7w6PxeIw7dWdVTWOVmiQuLL30tDLVmCB6V1Q9uR4xMLMiH8ZIV8C/F1HcD9gjZttMO48nOpgOXoQ9zhEY3wjXVX3ZaWwFwsnMzNaOCFAQizNDDtLXEUlDRYNWs0gcpbTGs7LwHJX+R/LXeunCOKD8BveuQspQ9MFW8RXqQZo8UE9RE1LJPwimE/mgScZMffuUBfxve+CSUtphADj4X657pakxOiQ5fD9mO8nYkiQCV7wDdCN5w02Y6ViBQfK9OrTHkW5KZEJfr6TTQy25K63s/VEubAZBSkaAP/9rh7d0iu2UqvOOCEX0u31Sz3PcFg5pjJlLlwkXORF/mFBHSUyYBTtYULr9dy+u5vkvWBb0oDFEG2veLE54OjSCTd+PDLoRMv0=
after_success:
- bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
env:
  matrix:
    secure: HrKxBTQotkh5PAq4x3Cgp2H8dNXGh4ucrIALzN3V4dhOzbp/LE8Yq76FMWxNeZh01PhUqSFtkYnBjARwgUVSDFThFSLK0daBMWnXgMI/Afhx1iVAK/b/qHEZVG01Dq/ar4ms6Fe9KD7BcNFhsyLR6dQ/fxbBKGZV48aAmTMN2Ko78tbcudPrRm0DfuxbdhDV8jh54VyaoaanM5Gj2m+/t+fjVfaqzRCYyfsOXD2Gbqmkr2l3Zbd+P6N932nFnvnCU5wcy1osRMmRVG+ptYrcsFQInUBPQF1upGPJ9uiVzrN/XNOZXWWoqo1HlzvzP5h9OGn5dNFfI3c3SKB1PmWA/22gTPvwvuGnoXbNFHwhmZNEbBcV+4ZdqYLSkqZpQr0NQy5QwGGkVjbQUVIuXvkHtg64QctDGBhnhyCIBD8Z3WweMSoRTImfKwHOggNHEqSlLiWwU600r19oOqLdgVI1TlH6WSR+Exzt/DXo64uq3XV/HPoW8zxr/GfSpIHiSu6XZcQzQscTNA71UMHOcEN4j66tIopiBkKcuaiN/A4WrvoG84Vvl2Ujn7TgxsPXB/WAfWD8KsllVzK7/H5Q9QsbJ0FKwCeky/6lEmiKz01DyTcPNR+q3yfd8cX55GGcc5g4WbHwRFWQnK+g+nfvkw07HWdcjia651CCGIV8avEV1dc=
