language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: nosetests --with-cov --cov-config .coveragerc --cov-report term-missing
notifications:
  email: false
before_install:
   echo "pass" > pass
after_success:
- bash <(curl -s https://codecov.io/bash) -t 1c738cf8-9578-472e-81a3-3bd0f1e2f57a
